---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  chef_omnibus_url: https://www.chef.io/chef/install.sh


platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
     - recipe[splunk_monitor::default]
    attributes:
      dev_mode: true
      splunk:
        accept_license: true
        monitors:
        - varlog:
            location: "/var/log/messages"
        scripts:
        - crashplandevices:
            location: "/opt/splunkforwarder/bin/scripts/cpdestination.sh"
            host: cp.biola.edu
            index: crashplan
